$(document).ready(function () {



	var count = 0;
	var subcount = 0;
	
// multipe images in series
	

	$('#m1').click(function() {	
		
		if (count == 0){          		// State flower illustrations
			subcount++;
				if (subcount == 5){
					subcount=0;
					}				
			$('#m1').attr('src', 'img/_design/b-flower' + subcount + '.jpg');
			$('h2').html(subcap0[subcount]);
		} else if (count == 1){          		// State map diagrams
			subcount++;
				if (subcount == 6){
					subcount=0;
					}				
			$('#m1').attr('src', 'img/_design/b-states' + subcount + '.jpg');
			$('h2').html(subcap1[subcount]);
		} else if (count == 2){          		// Verla
			subcount++;
				if (subcount == 3){
					subcount=0;
					}				
			$('#m1').attr('src', 'img/_design/b-verla' + subcount + '.jpg');
			$('h2').html(subcap2[subcount]);
		} else if (count == 3){          		// Ukraine
			subcount++;
				if (subcount == 8){
					subcount=0;
					}				
			$('#m1').attr('src', 'img/_design/b-ukraine' + subcount + '.jpg');
			$('h2').html(subcap3[subcount]);

		} else if (count == 4){          		// Emotion Archive
			subcount++;
				if (subcount == 11){
					subcount=0;
					}				
			$('#m1').attr('src', 'img/_design/b-emotion' + subcount + '.jpg');
			$('h2').html(subcap4[subcount]);	
		} else if (count == 5){          		// sensational weather
			subcount++;
				if (subcount == 13){
					subcount=0;
					}				
			$('#m1').attr('src', 'img/_design/b-weather' + subcount + '.jpg');
			$('h2').html(subcap5[subcount]);		
		} else if (count == 7){          		// icon catalog 
			subcount++;
				if (subcount == 7){
					subcount=0;
					}				
			$('#m1').attr('src', 'img/_design/b-catalog' + subcount + '.jpg');
			$('h2').html(subcap6[subcount]);	
		} else if (count == 8){          		// chairs
			subcount++;
				if (subcount == 5){
					subcount=0;
					}				
			$('#m1').attr('src', 'img/_design/b-chairs' + subcount + '.jpg');
			$('h2').html(subcap7[subcount]);	
		} else {
		subcount=0;	
		}						
		});

		console.log(subcount);
	
// SET TEXT FOR EACH OF THE IMAGES

	var caption  = ["Flower illustrations for the covers of infographic guidebooks about the different states | Red Clover, Vermont [&thinsp;1 of 5&thinsp;]",							// 0
					"Maps of different states. The guidebooks highlight some of the demographic differences between different areas of the United States [&thinsp;1 of 4&thinsp;]",	 	// 1								
					"Pattern studies and identity for Verla, a historic paper mill in Finland [&thinsp;1 of 3&thinsp;]", 																// 2
					"A collection of infographics about Ukraine [&thinsp;1 of 8&thinsp;]",  																							// 3
					"Emotion Archive : A collection of books that showcase examples of the four major emotions &mdash; sadness, anger, fear and joy [&thinsp;1 of 9&thinsp;]",  		// 5 
					"Sensational Weather : A series of postcards pairing actual headlines from </BR>weather.com with images of major disasters caused by extreme weather. [&thinsp;1 of 13&thinsp;]",  // 6
					"Selection from 500 patterns generated by a program written in <a href='http://www.processing.org'>processing</a>",  												// 7
					"Icon system and catalog, made in response to the exhibit <em>Graphic&thinsp;Design&thinsp;Now&thinsp;in&thinsp;Production</em>.</BR> The catalog diagrams different methods of form-making across a selection of 25 works from the exhibit. [&thinsp;1 of 7&thinsp;]", // 8
					"How to read the character of chairs: A poster project that pairs famous chairs with different </BR> personality traits &ndash; text is appropriated from a Phrenology textbook from the 1880's [&thinsp;1 of 5&thinsp;]", // 9
					"Illustration for an episode of Fathom's podcast <a href='http://www.fathom.info/ebd' target='blank'>Especially Big Data</a>", // 10
					"Valentine (letterpress print)", // 11
					]	

	var subcap0 = ["Flower illustrations for the covers of infographic guidebooks about the different states | Red Clover, Vermont [&thinsp;1 of 5&thinsp;]",
				   "Flower illustrations for the covers of infographic guidebooks about the different states | Forget-me-not, Alaska [&thinsp;2 of 5&thinsp;]",
				   "Flower illustrations for the covers of infographic guidebooks about the different states | California Poppy, California [&thinsp;3 of 5&thinsp;]",
				   "Flower illustrations for the covers of infographic guidebooks about the different states | Magnolia, Mississippi [&thinsp;4 of 5&thinsp;]",
				   "Flower illustrations for the covers of infographic guidebooks about the different states | Bluebell, Texas [&thinsp;5 of 5&thinsp;]",
					]


	var subcap1 = ["Maps of different states. The guidebooks highlight some of the demographic differences between different areas of the United States [&thinsp;1 of 6&thinsp;]",
				   "Each map highlights the ten population areas within the state [&thinsp;2 of 6&thinsp;]",
				   "The design is consistent between across the series so the different states can be easily compared  [&thinsp;3 of 6&thinsp;]",
				   "A comparison of city populations [&thinsp;4 of 6&thinsp;]",
				   "A comparison of city populations [&thinsp;5 of 6&thinsp;]",				   
				   "Set of three completed guidebooks [&thinsp;6 of 6&thinsp;]",
					]

	var subcap2 = ["Pattern studies and identity for Verla, a historic paper mill in Finland [&thinsp;1 of 3&thinsp;]",
				   "The pattern designs reference the 'V' in Verla, as well as the stacks of paper produced by the mill, and the surrounding forests [&thinsp;2 of 3&thinsp;]",
				   "The color palette is in reference to the historic brick used not only in the mill,</BR> but in the surrounding complexes that housed its workers [&thinsp;3 of 3&thinsp;]",
					]	

	var subcap3	= [ "A collection of infographics about Ukraine [&thinsp;1 of 8&thinsp;]",			
					"A collection of infographics about Ukraine [&thinsp;2 of 8&thinsp;]",
					"A collection of infographics about Ukraine [&thinsp;3 of 8&thinsp;]",
					"A collection of infographics about Ukraine [&thinsp;4 of 8&thinsp;]",
					"A collection of infographics about Ukraine [&thinsp;5 of 8&thinsp;]",
					"A collection of infographics about Ukraine [&thinsp;6 of 8&thinsp;]",
					"A collection of infographics about Ukraine [&thinsp;7 of 8&thinsp;]",	
					"A collection of infographics about Ukraine [&thinsp;8 of 8&thinsp;]",
					]

	var subcap4 = [ "Emotion Archive : A collection of books that showcase examples of the four major emotions &mdash; sadness, anger, fear and joy [&thinsp;1 of 9&thinsp;]", 
					"Emotion Archive : A collection of books that showcase examples of the four major emotions &mdash; sadness, anger, fear and joy [&thinsp;2 of 9&thinsp;]", 
					"Emotion Archive : A collection of books that showcase examples of the four major emotions &mdash; sadness, anger, fear and joy [&thinsp;3 of 9&thinsp;]", 
					"Emotion Archive : A collection of books that showcase examples of the four major emotions &mdash; sadness, anger, fear and joy [&thinsp;4 of 9&thinsp;]",
					"Emotion Archive : A collection of books that showcase examples of the four major emotions &mdash; sadness, anger, fear and joy [&thinsp;5 of 9&thinsp;]", 
					"Emotion Archive : A collection of books that showcase examples of the four major emotions &mdash; sadness, anger, fear and joy [&thinsp;6 of 9&thinsp;]",
					"Emotion Archive : A collection of books that showcase examples of the four major emotions &mdash; sadness, anger, fear and joy [&thinsp;7 of 9&thinsp;]",
					"Emotion Archive : A collection of books that showcase examples of the four major emotions &mdash; sadness, anger, fear and joy [&thinsp;8 of 9&thinsp;]", 
					"Emotion Archive : A collection of books that showcase examples of the four major emotions &mdash; sadness, anger, fear and joy [&thinsp;9 of 9&thinsp;]",	
					]							


	var subcap5 = [ "Sensational Weather : A series of postcards pairing actual headlines from </BR>weather.com with images of major disasters caused by extreme weather. [&thinsp;1 of 13&thinsp;]", 
					"Sensational Weather : A series of postcards pairing actual headlines from </BR>weather.com with images of major disasters caused by extreme weather. [&thinsp;2 of 13&thinsp;]", 
					"Sensational Weather : A series of postcards pairing actual headlines from </BR>weather.com with images of major disasters caused by extreme weather. [&thinsp;3 of 13&thinsp;]", 
					"Sensational Weather : A series of postcards pairing actual headlines from </BR>weather.com with images of major disasters caused by extreme weather. [&thinsp;4 of 13&thinsp;]",
					"Sensational Weather : A series of postcards pairing actual headlines from </BR>weather.com with images of major disasters caused by extreme weather. [&thinsp;5 of 13&thinsp;]", 
					"Sensational Weather : A series of postcards pairing actual headlines from </BR>weather.com with images of major disasters caused by extreme weather. [&thinsp;6 of 13&thinsp;]",
					"Sensational Weather : A series of postcards pairing actual headlines from </BR>weather.com with images of major disasters caused by extreme weather. [&thinsp;7 of 13&thinsp;]",
					"Sensational Weather : A series of postcards pairing actual headlines from </BR>weather.com with images of major disasters caused by extreme weather. [&thinsp;8 of 13&thinsp;]", 
					"Sensational Weather : A series of postcards pairing actual headlines from </BR>weather.com with images of major disasters caused by extreme weather. [&thinsp;9 of 13&thinsp;]",
					"Sensational Weather : A series of postcards pairing actual headlines from </BR>weather.com with images of major disasters caused by extreme weather. [&thinsp;10 of 13&thinsp;]",
					"Sensational Weather : A series of postcards pairing actual headlines from </BR>weather.com with images of major disasters caused by extreme weather. [&thinsp;11 of 13&thinsp;]", 
					"Sensational Weather : A series of postcards pairing actual headlines from </BR>weather.com with images of major disasters caused by extreme weather. [&thinsp;12 of 13&thinsp;]",			
					"Sensational Weather : A series of postcards pairing actual headlines from </BR>weather.com with images of major disasters caused by extreme weather. [&thinsp;13 of 13&thinsp;]",	
					]

	var subcap6 = ["Icon system and catalog, made in response to the exhibit <em>Graphic&thinsp;Design&thinsp;Now&thinsp;in&thinsp;Production</em>.</BR> The catalog diagrams different methods of form-making across a selection of 25 works from the exhibit. [&thinsp;1 of 7&thinsp;]",
				   "Icon system and catalog, made in response to the exhibit <em>Graphic&thinsp;Design&thinsp;Now&thinsp;in&thinsp;Production</em>.</BR> The catalog diagrams different methods of form-making across a selection of 25 works from the exhibit. [&thinsp;2 of 7&thinsp;]",
				   "Icon system and catalog, made in response to the exhibit <em>Graphic&thinsp;Design&thinsp;Now&thinsp;in&thinsp;Production</em>.</BR> The catalog diagrams different methods of form-making across a selection of 25 works from the exhibit. [&thinsp;3 of 7&thinsp;]",
				   "Icon system and catalog, made in response to the exhibit <em>Graphic&thinsp;Design&thinsp;Now&thinsp;in&thinsp;Production</em>.</BR> The catalog diagrams different methods of form-making across a selection of 25 works from the exhibit. [&thinsp;4 of 7&thinsp;]",
				   "Icon system and catalog, made in response to the exhibit <em>Graphic&thinsp;Design&thinsp;Now&thinsp;in&thinsp;Production</em>.</BR> The catalog diagrams different methods of form-making across a selection of 25 works from the exhibit. [&thinsp;5 of 7&thinsp;]",
				   "Icon system and catalog, made in response to the exhibit <em>Graphic&thinsp;Design&thinsp;Now&thinsp;in&thinsp;Production</em>.</BR> The catalog diagrams different methods of form-making across a selection of 25 works from the exhibit. [&thinsp;6 of 7&thinsp;]",
				   "Icon system and catalog, made in response to the exhibit <em>Graphic&thinsp;Design&thinsp;Now&thinsp;in&thinsp;Production</em>.</BR> The catalog diagrams different methods of form-making across a selection of 25 works from the exhibit. [&thinsp;7 of 7&thinsp;]",
					]

	var subcap7 = ["How to read the character of chairs: A poster project that pairs famous chairs with different </BR> personality traits &ndash; text is appropriated from a Phrenology textbook from the 1880's [&thinsp;1 of 5&thinsp;]",
				   "How to read the character of chairs: A poster project that pairs famous chairs with different </BR> personality traits &ndash; text is appropriated from a Phrenology textbook from the 1880's [&thinsp;2 of 5&thinsp;]",
				   "How to read the character of chairs: A poster project that pairs famous chairs with different </BR> personality traits &ndash; text is appropriated from a Phrenology textbook from the 1880's [&thinsp;3 of 5&thinsp;]", 
				   "How to read the character of chairs: A poster project that pairs famous chairs with different </BR> personality traits &ndash; text is appropriated from a Phrenology textbook from the 1880's [&thinsp;4 of 5&thinsp;]",
				   "How to read the character of chairs: A poster project that pairs famous chairs with different </BR> personality traits &ndash; text is appropriated from a Phrenology textbook from the 1880's [&thinsp;5 of 5&thinsp;]",
				   ]


// SET LARGE IMAGE WITH THUMBNAILS

	$('.b0').click(function() {
	    $('#m1').attr('src', 'img/_design/b-flower0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');	    count=0;
	    $("html, body").animate({ scrollTop: 0 }, 800);																							// State flowers
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');	
		$('#imgMain').css('width', '650px');
	});

	$('.b1').click(function() {
	    $('#m1').attr('src', 'img/_design/b-states0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		count=1;
	    $("html, body").animate({ scrollTop: 0 }, 800);																							// State maps
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');	 
	    $('#imgMain').css('width', '739px');		
	});																		

	$('.b2').click(function() {
	    $('#m1').attr('src', 'img/_design/b-verla0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		count=2;
	    $("html, body").animate({ scrollTop: 0 }, 800);														 									// Verla
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');				
	    $('#imgMain').css('width', '739px');												
	});

	$('.b3').click(function() {
		$('#m1').attr('src', 'img/_design/b-ukraine0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		count=3;
	    $("html, body").animate({ scrollTop: 0 }, 800);																							// Ukraine
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');											
	    $('#imgMain').css('width', '850px');
	});

	$('.b4').click(function() {
	    $('#m1').attr('src', 'img/_design/b-emotion0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		count=4;
	    $("html, body").animate({ scrollTop: 0 }, 800);														 									// Emotion archive
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');											
	    $('#imgMain').css('width', '850px'); 
	});

	$('.b5').click(function() {
	    $('#m1').attr('src', 'img/_design/b-weather0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		count=5;
	    $("html, body").animate({ scrollTop: 0 }, 800);																							// sensational weather
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');
	    $('#imgMain').css('width', '432px');	 
	});

	$('.b6').click(function() {
	    $('#m1').attr('src', 'img/_design/b-patterns.gif').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		count=6;
	    $("html, body").animate({ scrollTop: 0 }, 800);																							// Processing patterns 
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');
	    $('#imgMain').css('width', '550px');
	});

	$('.b7').click(function() {
	    $('#m1').attr('src', 'img/_design/b-catalog0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		count=7;
	    $("html, body").animate({ scrollTop: 0 }, 800);													 			  							// Icon catalog
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');
	    $('#imgMain').css('width', '739px');
	});
	$('.b8').click(function() {
	    $('#m1').attr('src', 'img/_design/b-chairs0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		count=8;
	    $("html, body").animate({ scrollTop: 0 }, 800);																							// chairs
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');											
	    $('#imgMain').css('width', '730px');
	});
	$('.b9').click(function() {
	    $('#m1').attr('src', 'img/_design/b-papers.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		count=9;
	    $("html, body").animate({ scrollTop: 0 }, 800);																							// EBD papers
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');
		$('#imgMain').css('width', '850px'); 
	});
	$('.b10').click(function() {
	    $('#m1').attr('src', 'img/_design/b-valentine.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%'); 	count=10;
	    $("html, body").animate({ scrollTop: 0 }, 800);																							// Valentine
	    $('h2').html(caption[count]).css('margin-top', '55px').css('margin-bottom', '55px');
		$('#imgMain').css('width', '390px'); 
	});


// clicking on any image box turns on large gallery box at top + H2 description text

	for (var j=0; j<20; j++){	
	$('.b' + j).click(function() {
		$('#main').css('display', 'inline-block');
		$('h2').css('display', 'inline-block');

		});
	$('.b' + j).hover(function() {
		$(this).fadeTo(210, 0.75).css('background-color', '#ffffff');
		}, function() {
		$(this).fadeTo(410, 1.0).css('background-color', 'none');
		});
	}

// ARROW key to advance image <-- && -->
console.log(count);

	 $(document).keydown(function(e){ 
		if (e.keyCode == 39) {  						// forward arrow
			count++;
			if(count == 11){ 							
			count=0;
			}
		} else if (e.keyCode == 37) { 					// back arrow
			count = count - 1;
			if(count == -1){
			count=10;									// total # of images on page * must be accurate for proper looping * 
			}	
		}
		$('h2').html(caption[count]);


	if (count == 0) {
	    $('#m1').attr('src', 'img/_design/b-flower0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');	    // state flowers																						// State flowers
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');	
		$('#imgMain').css('width', '650px');
	} else if (count == 1) {
	    $('#m1').attr('src', 'img/_design/b-states0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		// state diagrams																						// State maps
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');	 
	    $('#imgMain').css('width', '739px');		
	} else if (count == 2) {
	    $('#m1').attr('src', 'img/_design/b-verla0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		// verla													 									// Verla
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');				
	    $('#imgMain').css('width', '739px');												
	} else if (count == 3) {
		$('#m1').attr('src', 'img/_design/b-ukraine0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		// ukraine																						// Ukraine
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');											
	    $('#imgMain').css('width', '850px');
	} else if (count == 4) {
	    $('#m1').attr('src', 'img/_design/b-emotion0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		// emotion													 									// Emotion archive
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');											
	    $('#imgMain').css('width', '850px'); 
	} else if (count == 5) {
	    $('#m1').attr('src', 'img/_design/b-weather0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		// weather																						// sensational weather
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');
	    $('#imgMain').css('width', '432px');	 
	} else if (count == 6) {
	    $('#m1').attr('src', 'img/_design/b-patterns.gif').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		// processing																						// Processing patterns 
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');
	    $('#imgMain').css('width', '550px');
	} else if (count == 7) {
	    $('#m1').attr('src', 'img/_design/b-catalog0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		// catalog icons												 			  							// Icon catalog
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');
	    $('#imgMain').css('width', '739px');
	} else if (count == 8) {
	    $('#m1').attr('src', 'img/_design/b-chairs0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		// chairs																						// chairs
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');											
	    $('#imgMain').css('width', '730px');
	} else if (count == 9) {
	    $('#m1').attr('src', 'img/_design/b-papers.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		// papers ebd																						// EBD papers
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');
		$('#imgMain').css('width', '850px'); 
	} else if (count == 10) {
	    $('#m1').attr('src', 'img/_design/b-valentine.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%'); 	// valentine																						// Valentine
	    $('h2').html(caption[count]).css('margin-top', '55px').css('margin-bottom', '55px');
		$('#imgMain').css('width', '390px'); 
	} else if(count == 11){
			count=0;
		} else if (count == -1){
			count = 10;
		}	
	$('h2').html(caption[count]);		// captions each image 
	subcount=0;  						//resets subcount to zero after every click
	});	

// hover and click left arrow space

	$('#arrowR').click(function() {
	    count++;

	if (count == 0) {
	    $('#m1').attr('src', 'img/_design/b-flower0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');	    // state flowers																						// State flowers
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');	
		$('#imgMain').css('width', '650px');
	} else if (count == 1) {
	    $('#m1').attr('src', 'img/_design/b-states0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		// state diagrams																						// State maps
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');	 
	    $('#imgMain').css('width', '739px');		
	} else if (count == 2) {
	    $('#m1').attr('src', 'img/_design/b-verla0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		// verla													 									// Verla
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');				
	    $('#imgMain').css('width', '739px');												
	} else if (count == 3) {
		$('#m1').attr('src', 'img/_design/b-ukraine0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		// ukraine																						// Ukraine
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');											
	    $('#imgMain').css('width', '850px');
	} else if (count == 4) {
	    $('#m1').attr('src', 'img/_design/b-emotion0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		// emotion													 									// Emotion archive
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');											
	    $('#imgMain').css('width', '850px'); 
	} else if (count == 5) {
	    $('#m1').attr('src', 'img/_design/b-weather0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		// weather																						// sensational weather
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');
	    $('#imgMain').css('width', '432px');	 
	} else if (count == 6) {
	    $('#m1').attr('src', 'img/_design/b-patterns.gif').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		// processing																						// Processing patterns 
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');
	    $('#imgMain').css('width', '550px');
	} else if (count == 7) {
	    $('#m1').attr('src', 'img/_design/b-catalog0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		// catalog icons												 			  							// Icon catalog
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');
	    $('#imgMain').css('width', '739px');
	} else if (count == 8) {
	    $('#m1').attr('src', 'img/_design/b-chairs0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		// chairs																						// chairs
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');											
	    $('#imgMain').css('width', '730px');
	} else if (count == 9) {
	    $('#m1').attr('src', 'img/_design/b-papers.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		// papers ebd																						// EBD papers
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');
		$('#imgMain').css('width', '850px'); 
	} else if (count == 10) {
	    $('#m1').attr('src', 'img/_design/b-valentine.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%'); 	// valentine																						// Valentine
	    $('h2').html(caption[count]).css('margin-top', '55px').css('margin-bottom', '55px');
		$('#imgMain').css('width', '390px'); 
	} else if(count == 11){
		count=0;
		$('#m1').attr('src', 'img/_design/b-flower0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');	    // state flowers																						// State flowers
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');	
		$('#imgMain').css('width', '650px');
	}	
	$('h2').html(caption[count]);		// captions each image 
	subcount=0;  						//resets subcount to zero after every click
	});	


// hover and click right arrow space

	$('#arrowL').click(function() {
	    count = count - 1;
	if (count == 0) {
	    $('#m1').attr('src', 'img/_design/b-flower0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');	    // state flowers																						// State flowers
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');	
		$('#imgMain').css('width', '650px');
	} else if (count == 1) {
	    $('#m1').attr('src', 'img/_design/b-states0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		// state diagrams																						// State maps
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');	 
	    $('#imgMain').css('width', '739px');		
	} else if (count == 2) {
	    $('#m1').attr('src', 'img/_design/b-verla0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		// verla													 									// Verla
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');				
	    $('#imgMain').css('width', '739px');												
	} else if (count == 3) {
		$('#m1').attr('src', 'img/_design/b-ukraine0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		// ukraine																						// Ukraine
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');											
	    $('#imgMain').css('width', '850px');
	} else if (count == 4) {
	    $('#m1').attr('src', 'img/_design/b-emotion0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		// emotion													 									// Emotion archive
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');											
	    $('#imgMain').css('width', '850px'); 
	} else if (count == 5) {
	    $('#m1').attr('src', 'img/_design/b-weather0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		// weather																						// sensational weather
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');
	    $('#imgMain').css('width', '432px');	 
	} else if (count == 6) {
	    $('#m1').attr('src', 'img/_design/b-patterns.gif').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		// processing																						// Processing patterns 
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');
	    $('#imgMain').css('width', '550px');
	} else if (count == 7) {
	    $('#m1').attr('src', 'img/_design/b-catalog0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		// catalog icons												 			  							// Icon catalog
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');
	    $('#imgMain').css('width', '739px');
	} else if (count == 8) {
	    $('#m1').attr('src', 'img/_design/b-chairs0.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		// chairs																						// chairs
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');											
	    $('#imgMain').css('width', '730px');
	} else if (count == 9) {
	    $('#m1').attr('src', 'img/_design/b-papers.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%');		// papers ebd																						// EBD papers
	    $('h2').html(caption[count]).css('margin-top', '60px').css('margin-bottom', '50px');
		$('#imgMain').css('width', '850px'); 
	} else if (count == 10) {
	    $('#m1').attr('src', 'img/_design/b-valentine.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%'); 	// valentine																						// Valentine
	    $('h2').html(caption[count]).css('margin-top', '55px').css('margin-bottom', '55px');
		$('#imgMain').css('width', '390px'); 
	} else if(count == -1){
			count = 10;
		$('#m1').attr('src', 'img/_design/b-valentine.jpg').css('display', 'inline-block').css('object-fit', 'cover').css('width', '100%'); 	// valentine																						// Valentine
	    $('h2').html(caption[count]).css('margin-top', '55px').css('margin-bottom', '55px');
		$('#imgMain').css('width', '390px'); 
	}	
	$('h2').html(caption[count]);		// captions each image 
	subcount=0;  						//resets subcount to zero after every click
	});	

// hovering arrow to change opacity

	$('#arrowL').hover(function() {
	$('#arrowL').css('opacity', '1');		
	}, function() {
	$('#arrowL').css('opacity', '0.5');	
	});

	// hovering arrow to change opacity

	$('#arrowR').hover(function() {
	$('#arrowR').css('opacity', '1');		
	}, function() {
	$('#arrowR').css('opacity', '0.5');	
	});


// hovering email on about page

	$('#email').hover(function(){
	$(this).css('background-color', '#fff000').css('color', '#80B5FF'); 
	}, function(){
	$(this).css('background-color', '#E7E6F2').css('color', '#7194DE');	
	});
			
			
// hovering top navigation elements	

	$('#design').hover(function() {
	$('#design').css('opacity', 0.85).addClass('move').removeClass('return');

	}, function() {
			$('#design').css('opacity', 1).addClass('return').removeClass('move');		
	});

	$('#drawing a').hover(function() {
			$('#drawing').css('opacity', 1).addClass('move').removeClass('return');
			$('#drawing a').css('color', '#143DE0');
			$('#design a').css('color', '#6F98DE');
	}, function() {
			$('#drawing').css('opacity', 0.75).addClass('return').removeClass('move');
			$('#drawing a').css('color', '#6F98DE');
			$('#design a').css('color', '#143DE0');
	});

	$('#gifs a').hover(function() {
			$('#gifs').css('opacity', 1).addClass('move').removeClass('return');
			$('#gifs a').css('color', '#143DE0');
			$('#design a').css('color', '#6F98DE');
	}, function() {
			$('#gifs').css('opacity', 0.75).addClass('return').removeClass('move');
			$('#gifs a').css('color', '#6F98DE');
			$('#design a').css('color', '#143DE0');
	});

	$('#motion a').hover(function() {
			$('#motion').css('opacity', 1).addClass('move').removeClass('return');
			$('#motion a').css('color', '#143DE0');
			$('#design a').css('color', '#6F98DE');
	}, function() {
			$('#motion').css('opacity', 0.75).addClass('return').removeClass('move');
			$('#motion a').css('color', '#6F98DE');
			$('#design a').css('color', '#143DE0');
	});

		$('#hola a').hover(function() {
			$('#hola').css('opacity', 1).addClass('move').removeClass('return');
			$('#hola a').css('color', '#143DE0');
			$('#design a').css('color', '#6F98DE');
	}, function() {
			$('#hola').css('opacity', 0.75).addClass('return').removeClass('move');
			$('#hola a').css('color', '#6F98DE');
			$('#design a').css('color', '#143DE0');
	});

	// hover and clicking for MOBILE size

	$('h4').click(function() {							
		$('.menuSub').css('opacity', '1').css('height', '40px').css('padding-bottom', '8px');
		$('a h5').css('display', 'block');		
	});

	$('h4').on("tap",function() {								
		$('.menuSub').css('opacity', '1').css('height', '40px').css('padding-bottom', '8px');
		$('a h5').css('display', 'block');		
	});


	$('h4').hover(function() {
		$('.menuSub').css('opacity', '1').css('height', '40px').css('padding-bottom', '8px');
		$('a h5').css('display', 'block');				
	});

	$('.menuSub').hover(function() {
	$(this).css('opacity', '0.7'); 
	}, function(){
	$(this).css('opacity', '1.0');	
	});


// resizing for different screen widths and mobile on load

	$(window).load(function(){
	console.log(window.innerWidth, window.innerHeight);  
	
		if (window.innerWidth > 1080){							// fits the header over the boxes for scrolling
			$('#head').css('width', '85%');
		} else if (window.innerWidth < 1080 && window.innerWidth > 900){
			$('#head').css('width', '80%');
		} else {
			$('#head').css('width', '75%');
		}

		if (window.innerWidth > 760){
			$('#head').css('opacity', '1');
			$('#drawing, #hola, #design, #sketch, #arrowL, #arrowR').css('display', 'inline-block');
			$('#head .headlink').css('height', '45px');
			$('#box').css('margin-left', '0').css('height', '2170');
			$('#boxhidden').css('diplay', 'none');
			$('#box').css('margin-left', '5%').css('margin-right', '5%').css('width', '90%');	// restore dark background margins
			$('#menu').css('display', 'none');
			$('#head').css('display', 'block');
			$('#menu').css('display', 'none');
			$('#mobilehead').css('display', 'none');
			$('#body').css('display', 'block');
			$('.menuSub').css('height', '0px').css('padding-bottom', '0px');	// disappear mobile menu box
			$('h5').css('opacity', '0.0');										// disappear mobile menu text
			$('h1').css('display', 'block');
			$('#main').css({
					'margin-left': '20px',
					'width': '100%',
					 });
			for (var j=0; j<20; j++){	
			$('.b' + j).css({
					'width': '250px',
					'height': '240px',
					'padding-right': '0%',
					'background-color': '#E7E6F2',
					 });
			}	
		} else {

			$('#box').css({
					'margin-left': '0px',
					'margin-right': '0%',
					'width': '100%', // kill dark background margins
					'min-width': '400px', // can't shrink less than size of phone screen
					'height': '3200px', // longer window for mobile
					});
			$('#drawing, #hola, #design, #sketch, #arrow').css('display', 'none');
			$('#menu').css('display', 'inline').css('background-color', '#59D6FF');
			$('#mobilehead').css('display', 'inline-block');
			$('#body').css('display', 'none');
			$('h1').css('display', 'none');
			$('#head').css('display', 'none');
			$('.imgMobile').css('display', 'inline-block');
			$('#main').css({
					'margin-left': '0px',
					'width': '100%',
			});				
		}
	});

// resizing for different screen widths and mobile on resize

	$(window).resize(function(){
	console.log(window.innerWidth, window.innerHeight);  


		if (window.innerWidth > 1080){							// fits the header over the boxes for scrolling
			$('#head').css('width', '85%');
		} else if (window.innerWidth < 1080 && window.innerWidth > 900){
			$('#head').css('width', '80%');
		} else {
			$('#head').css('width', '75%');
		}

		if (window.innerWidth > 760){

			$('#head').css('opacity', '1');
			$('#drawing, #hola, #design, #sketch, #arrowL, #arrowR').css('display', 'inline-block');
			$('#head .headlink').css('height', '45px');
			$('#box').css('margin-left', '0').css('height', '2170');
			$('#boxhidden').css('diplay', 'none');
			$('#box').css('margin-left', '5%').css('margin-right', '5%').css('width', '90%');	// restore dark background margins
			$('#menu').css('display', 'none');
			$('#head').css('display', 'block');
			$('#menu').css('display', 'none');
			$('#mobilehead').css('display', 'none');
			$('#body').css('display', 'block');
			$('.menuSub').css('height', '0px').css('padding-bottom', '0px');	// disappear mobile menu box
			$('h5').css('opacity', '0.0');										// disappear mobile menu text
			$('h1').css('display', 'block');
			$('#main').css({
					'margin-left': '20px',
					'width': '100%',
					 });

			for (var j=0; j<20; j++){	
			$('.b' + j).css({
					'width': '250px',
					'height': '240px',
					'padding-right': '0%',
					'background-color': '#E7E6F2',
					 });
			}	
		} else {

			$('#box').css({
					'margin-left': '0px',
					'margin-right': '0%',
					'width': '100%', // kill dark background margins
					'min-width': '400px', // can't shrink less than size of phone screen
					'height': '3200px', // longer window for mobile
					});
			$('#drawing, #hola, #design, #sketch, #arrow').css('display', 'none');
			$('#menu').css('display', 'inline').css('background-color', '#59D6FF');
			$('#mobilehead').css('display', 'inline-block');
			$('#body').css('display', 'none');
			$('h1').css('display', 'none');
			$('#head').css('display', 'none');
			$('.imgMobile').css('display', 'inline-block');
			$('#main').css({
					'margin-left': '0px',
					'width': '100%',
					});				
		}
	});


});

