var captions = [ "This is an explainer paragraph with a little more background for the casting decisions and character roles.
				   Mentions cases where mother might have been relatively young, but age gap is scientificially impossible.",
				  "Alexander",
				  "Bye Bye Birdie",
				  "The Green Years",
				  "The Manchurian Candidate",
				  "Joey",
				  "Star Trek",
				  "North by Northwest is as perfect a movie as they come, so it's hard to criticize,
				  but the seven year age gap between Cary Grant and Jessie Royce Landis is just silly."
				  "Star Trek",
				  "Star Trek",
				  "Star Trek",
				  "Star Trek",
				  "Star Trek",
				  "Star Trek",
				  "Star Trek",
				  "Star Trek",
				  "Star Trek",
				  "Star Trek",
				  "Star Trek",
				  "Star Trek",
				  "Star Trek",
				  "Star Trek",
				  "Star Trek",
				]